/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1s12017_201403877;

import java.io.File;
import java.io.IOException;
import java.util.List;
import org.jdom2.Document;
import org.jdom2.Element;
import org.jdom2.JDOMException;
import org.jdom2.input.SAXBuilder;
import java.util.concurrent.ThreadLocalRandom;
/**
 *
 * @author CodigoG
 */
public class MenuPrincipal extends javax.swing.JFrame {

    ListaPalabraDiccionario palabras = new ListaPalabraDiccionario();
    int a = 12;
    int b = 2;
    int c = 4;
    int d = 5;
    int e = 12;
    int f = 1;
    int g = 2;
    int h = 2;
    int i = 6;
    int j = 1;
    //int k = ;
    int l = 4;
    int m = 2;
    int n = 5;
    int ñ = 1;
    int o = 9;
    int p = 2;
    int q = 1;
    int r = 5;
    int s = 6;
    int t = 4;
    int u = 5;
    int v = 1;
    //int w = ;
    int x = 1;
    int y = 1;
    int z = 1;
            
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        initComponents();
        jButton2.setEnabled(false);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Leer Archivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Jugar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jButton1)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jButton1)
                .addGap(33, 33, 33)
                .addComponent(jButton2)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SAXBuilder builder = new SAXBuilder();
        jFileChooser1.showOpenDialog(this);
        //File xmlFile = new File("C:\\Users\\CodigoG\\Desktop\\prueba.xml");
        File xmlFile = jFileChooser1.getSelectedFile();
        
        try{
            Document document = (Document)builder.build(xmlFile);            
            Element rootNode = document.getRootElement();
            List list = rootNode.getChildren();            
            
            for (int i = 0; i < list.size(); i++) {
                Element node = (Element)list.get(i);
                if (node.getName() == "dimension"){
                    //System.out.println("Dimension: " + node.getValue());
                }
                if (node.getName() == "dobles"){
                    List listTemp = node.getChildren();
                    System.out.println("Dobles:");
                    for (int j = 0; j < listTemp.size(); j++) {
                        Element node11 = (Element)listTemp.get(j);                        
                        /*System.out.println("Valor x: " + node11.getChildText("x"));
                        System.out.println("Valor y: " + node11.getChildText("y"));*/
                    }
                }        
                if (node.getName() == "triples"){
                    List listTemp = node.getChildren();
                    System.out.println("Triples:");
                    for (int j = 0; j < listTemp.size(); j++) {
                        Element node11 = (Element)listTemp.get(j);                        
                        /*System.out.println("Valor x: " + node11.getChildText("x"));
                        System.out.println("Valor y: " + node11.getChildText("y"));*/
                    }
                }
                if (node.getName() == "diccionario"){
                    List listTemp = node.getChildren();
                    System.out.println("Palabras:");
                    for (int j = 0; j < listTemp.size(); j++) {
                        Element node11 = (Element)listTemp.get(j);
                        palabras.agregarFinal(node11.getValue().toLowerCase());
                        //System.out.println(node11.getValue());                       
                    }
                }
            }
            jButton2.setEnabled(true);
            palabras.mostrarElementos();
        }
        catch(IOException io){
            System.out.println(io.getMessage());
        } catch (JDOMException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        /*AddJugadores añadir = new AddJugadores();
        añadir.setVisible(true);
        this.setVisible(false);*/
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
                
            }
        });
    }

    protected void añadirCola(){
        int numeroAscii = ThreadLocalRandom.current().nextInt(65, 90);
        System.out.printf("%c",numeroAscii);
        
        switch (numeroAscii){
            case 'A':
                if (a>0){
                    //Nodo.letra = A
                    //Nodo.valor = 1
                    // a--;
                }
                break;
            case 'B':
                break;
            case 'C':
                break;
            case 'D':
                break;
            case 'E':
                break;
            case 'F':
                break;
            case 'G':
                break;
            case 'H':
                break;
            case 'I':
                break;
            case 'J':
                break;
            case 'L':
                break;
            case 'M':
                break;
            case 'N':
                break;
            case 'O':
                break;
            case 'P':
                break;
            case 'Q':
                break;
            case 'R':
                break;
            case 'S':
                break;
            case 'T':
                break;
            case 'U':
                break;
            case 'V':
                break;
            case 'X':
                break;
            case 'Y':
                break;
            case 'Z':
                break;
            default:
                
        } 
    } 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables
}
